# Generated by Django 3.0.8 on 2020-11-18 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sol', models.IntegerField()),
                ('max_temp', models.CharField(max_length=15)),
                ('min_temp', models.CharField(max_length=15)),
                ('avg_temp', models.CharField(max_length=15)),
                ('season', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
