# Generated by Django 3.0.8 on 2020-11-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201118_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperature',
            name='Sol',
            field=models.CharField(max_length=10),
        ),
    ]
