# Generated by Django 3.0.8 on 2020-11-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201118_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperature',
            name='avg_press',
            field=models.CharField(default='NaN', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='avg_wind',
            field=models.CharField(default='NaN', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='direction',
            field=models.CharField(default='NaN', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='max_press',
            field=models.CharField(default='NaN', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='max_wind',
            field=models.CharField(default='NaN', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='min_press',
            field=models.CharField(default='NaN', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temperature',
            name='min_wind',
            field=models.CharField(default='NaN', max_length=15),
            preserve_default=False,
        ),
    ]
